// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMatiVk75eQ6p2HmXBCAEd5bvQjrgwhqw',
    appId: '1:260406970172:web:c4945ea32826cc82794039',
    messagingSenderId: '260406970172',
    projectId: 'severance-260f3',
    authDomain: 'severance-260f3.firebaseapp.com',
    storageBucket: 'severance-260f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm2j-ZlfK0X8yQxKUs8D6pucZYEjry1cQ',
    appId: '1:260406970172:android:e2388db4a9362d4e794039',
    messagingSenderId: '260406970172',
    projectId: 'severance-260f3',
    storageBucket: 'severance-260f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdbvjCl8W0BZQ5AOwlt7u6jEjSCQ0UkEQ',
    appId: '1:260406970172:ios:034c5e36ca7c329b794039',
    messagingSenderId: '260406970172',
    projectId: 'severance-260f3',
    storageBucket: 'severance-260f3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdbvjCl8W0BZQ5AOwlt7u6jEjSCQ0UkEQ',
    appId: '1:260406970172:ios:034c5e36ca7c329b794039',
    messagingSenderId: '260406970172',
    projectId: 'severance-260f3',
    storageBucket: 'severance-260f3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMatiVk75eQ6p2HmXBCAEd5bvQjrgwhqw',
    appId: '1:260406970172:web:a14b98dae7fa79a3794039',
    messagingSenderId: '260406970172',
    projectId: 'severance-260f3',
    authDomain: 'severance-260f3.firebaseapp.com',
    storageBucket: 'severance-260f3.firebasestorage.app',
  );
}
